---

# Change to make non-empty commit and trigger push event
# rel: 0

stages:
  - .guard
  - lint
  - test
  - build
  - api-client

variables:
  # Set 0 to disable linting jobs
  LINTING_ENABLED: true
  TESTING_ENABLED: false
  GEN_API_CLIENT_ENABLED: false

include:
  - project: 'saltbox/ci-lib'
    file: 'build-image.yml'
  - project: 'saltbox/ci-lib'
    file: 'def-branch-merge-guard.yml'

.lint-job:
  stage: lint
  image: python:3.12-alpine
  before_script:
    - apk add git
    - apk add uv
    - uv sync --dev
  cache:
    paths:
      - '.venv/'
  rules:
    - if: $LINTING_ENABLED == 'true'

ruff:
  extends: .lint-job
  script: uv run ruff check app # --select I --fix

mypy:
  extends: .lint-job
  script: uv run mypy app

Build audit image for tag:
  stage: build
  extends: .build-image
  variables:
    TARGET: main
    IMAGE_TAG: '$CI_COMMIT_TAG'
  rules:
    - if: '$CI_COMMIT_TAG'


Build audit image for branch:
  stage: build
  extends: .build-image
  variables:
    TARGET: main
    IMAGE_TAG: '$CI_COMMIT_BRANCH'
  rules:
    - if: '$CI_COMMIT_BRANCH'


Trigger API Client pipeline:
  stage: api-client
  variables:
    MODULE_NAME: app
    SALTBOX_ENV_FILE: 'tests/test.env'
    GEN_OPENAPI_CMD: python3 './${MODULE_NAME}/utils/generate_openapi.py'
  trigger:
    include:
      - project: 'saltbox/ci-lib'
        file: 'gen-api-client.yml'
    strategy: mirror
  rules:
    - if: $CI_PIPELINE_SOURCE == 'push'
    - if: $GEN_API_CLIENT_ENABLED == 'true'
