FROM ghcr.io/astral-sh/uv:bookworm-slim AS builder

ENV UV_COMPILE_BYTECODE=1
ENV UV_LINK_MODE=copy
ENV UV_PYTHON_INSTALL_DIR=/python
ENV UV_PYTHON_PREFERENCE=only-managed

RUN apt-get update && apt-get install -y git \
    && rm -rf /var/lib/apt/lists/*
RUN uv python install 3.12

WORKDIR /src

COPY pyproject.toml uv.lock README.md ./
COPY ./app /src/app
RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --locked --no-install-project --no-dev
RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --locked --no-dev


FROM builder AS dev-builder
COPY ./app /src/app
RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --locked


FROM debian:bookworm-slim AS base

RUN groupadd --system --gid 999 nonroot \
 && useradd --system --gid 999 --uid 999 --create-home nonroot

COPY --from=builder --chown=nonroot:nonroot /python /python
COPY --from=builder --chown=nonroot:nonroot /src /src
COPY --chown=nonroot:nonroot docker/entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod 755 /usr/local/bin/entrypoint.sh

ENV PATH="/src/.venv/bin:$PATH"

USER nonroot
WORKDIR /src

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]

FROM base AS dev
USER root
COPY --from=dev-builder --chown=nonroot:nonroot /src /src
USER nonroot
ENV DEV_MODE=1

FROM base AS main
ENV DEV_MODE=0
